---
name: govfact
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: gov_facts
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: gov_facts
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
    - govfacts_network

  web:
    build:
      context: ./app
    ports:
      - 8000:8000
      - 5678:5678
    secrets:
      - db_password
    environment:
      DEBUG: "True"
      POSTGRES_HOST: db
      POSTGRES_DB: gov_facts
      POSTGRES_USER: gov_facts
    networks:
      - govfacts_network
    depends_on:
      - db

secrets:
  db_password:
    file: secrets/db_password.txt

volumes:
  postgres_data:

networks:
  govfacts_network:
    driver: bridge