---
services:
    devcontainer:
        image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
        networks:
            - dev
        volumes:
            - ..:/workspaces:cached
        command: bash -c "sleep infinity"

    postgres:
        image: postgres:17.2
        environment:
            - POSTGRES_PASSWORD=test
            - POSTGRES_USER=test
            - POSTGRES_DB=test
        networks:
            - dev
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql

    dbgate:
        image: dbgate/dbgate
        restart: always
        ports:
            - '3030:3000'
        volumes:
            - dbgate-data:/root/.dbgate
        environment:
            CONNECTIONS: postgres

            LABEL_postgres: Postgres
            SERVER_postgres: postgres
            USER_postgres: test
            PASSWORD_postgres: test
            PORT_postgres: 5432
            ENGINE_postgres: postgres@dbgate-plugin-postgres

        networks:
          - dev

networks:
    dev:

volumes:
    postgres-data:
    dbgate-data: